version: "3.9"
services:
  scrapy:
    container_name: scraper
    image: python:slim
    build:
      context: ./smartScraper
      target: prod
    volumes:
    - ./scrape:/scrape
    ports:
      - 5003:5000
      - 5678:5678
